### ISSUE TITLE
Unable to upgrade to v0.21.0

### ISSUE THREAD

**Issue by sharvit** [patternfly/patternfly-react#136]
Hi,

I am having this error when trying to update `patternfly-react` and run `npm install`

```bash
1208 verbose stack Error: patternfly-react@0.21.0 postinstall: `nvmrc-check --node $(cat .nvmrc)`
1208 verbose stack spawn ENOENT
1208 verbose stack     at ChildProcess.<anonymous> (/home/asharvit/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
1208 verbose stack     at emitTwo (events.js:126:13)
1208 verbose stack     at ChildProcess.emit (events.js:214:7)
1208 verbose stack     at maybeClose (internal/child_process.js:925:16)
1208 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1209 verbose pkgid patternfly-react@0.21.0
1210 verbose cwd /home/asharvit/Projects/theforeman/foreman
1211 verbose Linux 4.13.16-302.fc27.x86_64
1212 verbose argv "/home/asharvit/.nvm/versions/node/v8.9.3/bin/node" "/home/asharvit/.nvm/versions/node/v8.9.3/bin/npm" "install"
1213 verbose node v8.9.3
1214 verbose npm  v5.6.0
1215 error file sh
1216 error code ELIFECYCLE
1217 error errno ENOENT
1218 error syscall spawn
1219 error patternfly-react@0.21.0 postinstall: `nvmrc-check --node $(cat .nvmrc)`
1219 error spawn ENOENT
1220 error Failed at the patternfly-react@0.21.0 postinstall script.
1220 error This is probably not a problem with npm. There is likely additional logging output above.
1221 verbose exit [ 1, true ]
```

Tried to create a `.nvmrc` file but it didn't affect the error.

**Comment by priley86** [comment]
@sharvit ok now?

**Comment by sharvit** [comment]
@priley86, yes! Thanks for the fast fix  :tada:
