### ISSUE TITLE
Problem with missing styles "badge"

### ISSUE THREAD

**Issue by martinpovolny** [patternfly/patternfly-react#1711]
```
./node_modules/@patternfly/react-core/dist/esm/components/Select/Select.js 193:23-40
"export 'badge' (imported as 'badgeStyles') was not found in '../../@patternfly/patternfly/components/Badge/badge.css.js'
    at HarmonyImportSpecifierDependency._getErrors (/home/martin/Projects/topology-inventory-ui/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:113:11)
    at HarmonyImportSpecifierDependency.getWarnings (/home/martin/Projects/topology-inventory-ui/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:60:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/martin/Projects/topology-inventory-ui/node_modules/webpack/lib/Compilation.js:1326:24)
    at Compilation.finish (/home/martin/Projects/topology-inventory-ui/node_modules/webpack/lib/Compilation.js:1137:9)
    at hooks.make.callAsync.err (/home/martin/Projects/topology-inventory-ui/node_modules/webpack/lib/Compiler.js:545:17)
    at _done (eval at create (/home/martin/Projects/topology-inventory-ui/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at _err1 (eval at create (/home/martin/Projects/topology-inventory-ui/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:32:22)
    at _addModuleChain (/home/martin/Projects/topology-inventory-ui/node_modules/webpack/lib/Compilation.js:1065:12)
    at processModuleDependencies.err (/home/martin/Projects/topology-inventory-ui/node_modules/webpack/lib/Compilation.js:981:9)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./node_modules/@patternfly/react-core/dist/esm/components/Select/index.js
 @ ./node_modules/@patternfly/react-core/dist/esm/components/index.js
 @ ./node_modules/@patternfly/react-core/dist/esm/index.js
 @ ./node_modules/@red-hat-insights/insights-frontend-components/components/Notifications.js
 @ ./src/App.js
 @ ./src/entry-dev.js
 @ multi ./src/entry-dev.js
vendor.js:308723 ｢hot｣ ./node_modules/@patternfly/react-core/dist/esm/components/Select/Select.js 193:42-63
```

I tried upgrading to latest versions of everything. The stacktrace changes, but the
`"export 'badge' (imported as 'badgeStyles') was not found in...` stays.

**Comment by AllenBW** [comment]
OH SNAP! Ditto on this too, I was just kinda ignoring it.. but yeah Insights is feeling this too

```
WARNING in ./node_modules/@patternfly/react-table/node_modules/@patternfly/react-core/dist/esm/components/Select/Select.js 193:23-40
"export 'badge' (imported as 'badgeStyles') was not found in '../../@patternfly/patternfly/components/Badge/badge.css.js'
 @ ./node_modules/@patternfly/react-table/node_modules/@patternfly/react-core/dist/esm/components/Select/index.js
 @ ./node_modules/@patternfly/react-table/node_modules/@patternfly/react-core/dist/esm/components/index.js
 @ ./node_modules/@patternfly/react-table/node_modules/@patternfly/react-core/dist/esm/index.js
 @ ./node_modules/@patternfly/react-table/dist/esm/components/Table/RowWrapper.js
 @ ./node_modules/@patternfly/react-table/dist/esm/components/Table/index.js
 @ ./node_modules/@patternfly/react-table/dist/esm/components/index.js
 @ ./node_modules/@patternfly/react-table/dist/esm/index.js
 @ ./src/PresentationalComponents/RulesTable/RulesTable.js
 @ ./src/SmartComponents/Rules/ListRules.js
 @ ./src/SmartComponents/Rules/Rules.js
 @ ./src/Routes.js
 @ ./src/App.js
 @ ./src/entry-dev.js
 @ multi (webpack)-dev-server/client?http://localhost:8002 (webpack)/hot/dev-server.js ./src/entry-dev.js

WARNING in ./node_modules/@patternfly/react-table/node_modules/@patternfly/react-core/dist/esm/components/Select/Select.js 193:42-63
"export 'modifiers' (imported as 'badgeStyles') was not found in '../../@patternfly/patternfly/components/Badge/badge.css.js'
 @ ./node_modules/@patternfly/react-table/node_modules/@patternfly/react-core/dist/esm/components/Select/index.js
 @ ./node_modules/@patternfly/react-table/node_modules/@patternfly/react-core/dist/esm/components/index.js
 @ ./node_modules/@patternfly/react-table/node_modules/@patternfly/react-core/dist/esm/index.js
 @ ./node_modules/@patternfly/react-table/dist/esm/components/Table/RowWrapper.js
 @ ./node_modules/@patternfly/react-table/dist/esm/components/Table/index.js
 @ ./node_modules/@patternfly/react-table/dist/esm/components/index.js
 @ ./node_modules/@patternfly/react-table/dist/esm/index.js
 @ ./src/PresentationalComponents/RulesTable/RulesTable.js
 @ ./src/SmartComponents/Rules/ListRules.js
 @ ./src/SmartComponents/Rules/Rules.js
 @ ./src/Routes.js
 @ ./src/App.js
 @ ./src/entry-dev.js
```

**Comment by AllenBW** [comment]
@redallen any way yah can help prioritize this fellow Allen? 🙏 🤗 🙇‍♀️

**Comment by redallen** [comment]
Sorry, but hold tight for now. Once we do our next release this problem _should_ be fixed. The import should be `import badgeStyles from '@patternfly/patternfly/components/Badge/badge.css.js'` instead of `import * as badgeStyles from '@patternfly/patternfly/components/Badge/badge.css.js'` in `Select.js` and we should have the latest version of `@patternfly/patternfly` that has those badge styles.

**Comment by dmsimard** [comment]
I'm hitting this as well and I'm a bit of a patternfly/react noob. Is there a workaround available until the fix lands and is released ?

**Comment by redallen** [comment]
If all goes well, we'll be able to release today. There's not an easy way right now. Sorry!

**Comment by dmsimard** [comment]
@redallen thanks, I'll hang in there :)

**Comment by redallen** [comment]
If there are any brave beta testers, try react-core@3.1.1 and let me know if the problem is still there!

**Comment by karangarg45** [comment]
@redallen Yes the error seems to go away with the 3.1.3 release.

**Comment by redallen** [comment]
Thanks for letting me know! Have fun with PF4 :)

**Comment by martinpovolny** [comment]
Not fixed for me, probably because of:
https://github.com/RedHatInsights/insights-frontend-components/blob/master/package.json#L16

**Comment by martinpovolny** [comment]
I tried various versions but did not find a working combination of PF and Insights components that would work w/o warnings.

**Comment by ricardozanini** [comment]
I'm seeing this error here also. Same as @martinpovolny. Also, I'm note ready to move to PF4 yet. Is there any chance to backport this fix to PF3?

**Comment by redallen** [comment]
This error is because we used to have an invalid import `import badgeStyles from '@patternfly/patternfly/components/Badge/badge.css';` in [Select.js](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Select/Select.js). This was fixed in #1656 and available in @patternfly/react-core@3.1.1 or greater. What version of react-core are you using @ricardozanini ?

**Comment by ricardozanini** [comment]
Thanks for replying!

I'm using `2.11.1`

**Comment by redallen** [comment]
Ah, we currently don't backport bugfixes, but we'll certainly consider it moving forward with more cases like yours. However, if you're just using PF3, why are you using react-core? It's PF4.

**Comment by ricardozanini** [comment]
@redallen TBH I'm with a very short schedule and once I upgraded to 3.x version, I faced the following error: 

```
ERROR in ../node_modules/@patternfly/react-core/dist/styles/assets/images/pfbg_576.jpg 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ../node_modules/@patternfly/react-core/dist/esm/@patternfly/patternfly/components/BackgroundImage/background-image.css (../node_modules/css-loader!../node_modules/@patternfly/react-core/dist/esm/@patternfly/patternfly/components/BackgroundImage/background-image.css) 7:225-284
 @ ../node_modules/@patternfly/react-core/dist/esm/@patternfly/patternfly/components/BackgroundImage/background-image.css
 @ ../node_modules/@patternfly/react-core/dist/esm/@patternfly/patternfly/components/BackgroundImage/background-image.css.js
 @ ../node_modules/@patternfly/react-core/dist/esm/components/BackgroundImage/BackgroundImage.js
 @ ../node_modules/@patternfly/react-core/dist/esm/components/BackgroundImage/index.js
 @ ../node_modules/@patternfly/react-core/dist/esm/components/index.js
 @ ../node_modules/@patternfly/react-core/dist/esm/index.js
 @ ./component/operator-wizard/OperatorWizard.js
 @ ./component/Main.js
 @ ./index.js
 @ multi ./index.js
```

Not sure why and don't have time to investigate it right now. Tried to look into the docs to figure something out, but I'm too newbie with front-end stuff that I couldn't figure out how to exactly upgrade. Haven't found any docs about PF3 -> PF4 upgrade on React env (didn't look that much though).

Can you help me figure that out? Should be a really minor thing. :/

**Comment by redallen** [comment]
This is because Wizard uses BackgroundImage which imports a jpg. Configure your webpack to use [url loader](https://github.com/webpack-contrib/url-loader#getting-started) for jpgs. The config snippet there + `npm install`ing it should be all you need.

**Comment by ricardozanini** [comment]
@redallen +++++ you're a life saver, man! worked like a charm!!!! MANY THANKS. If you're a Red Hatter, ping me. I own you.
