### ISSUE TITLE
Issue after install again repo

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#410]
### Reproduce with yarn 1.3.2

- clone repo
- yarn install

### Error

```bash
[aljesusg@alberto ~/Projects/patternfly-react (master)]$ yarn install
yarn install v1.3.2
error An unexpected error occurred: "patterns.map is not a function".
info If you think this is a bug, please open a bug report with the information provided in "/Users/aljesusg/Projects/patternfly-react/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
### Trace ERROR

```bash
Trace:
  TypeError: patterns.map is not a function
      at /usr/local/lib/node_modules/yarn/lib/cli.js:54024:78
      at Generator.next (<anonymous>)
      at step (/usr/local/lib/node_modules/yarn/lib/cli.js:92:30)
      at /usr/local/lib/node_modules/yarn/lib/cli.js:110:14
      at new Promise (<anonymous>)
      at new F (/usr/local/lib/node_modules/yarn/lib/cli.js:29389:28)
      at /usr/local/lib/node_modules/yarn/lib/cli.js:89:12
      at Config.resolveWorkspaces (/usr/local/lib/node_modules/yarn/lib/cli.js:54060:7)
      at /usr/local/lib/node_modules/yarn/lib/cli.js:21998:49
      at Generator.next (<anonymous>)
```

### How to FIX

Upgrade yarn to >=1.5.1
We should add in the Readme this requirement

**Comment by dmiller9911** [comment]
This is now listed here:
https://github.com/patternfly/patternfly-react#node-environment

It is also making use of the engines field in package.json now.  When I tested it, I did see the error that I needed to upgrade.  I am not sure why it did not show there though. I will take a look.

**Comment by aljesusg** [comment]
oo I didn't see it, yes I think that we should throw a message or something
