### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@patternfly%2freact-core - Not found

### ISSUE THREAD

**Issue by vcarceler** [patternfly/patternfly-react#4666]
Trying to install PatternFly React npm can't find https://registry.npmjs.org/@patternfly%2freact-core

Steps to reproduce.

`npm install @patternfly/react-core --save`

Example output on Ubuntu 20.04.

```
usuario@laika:~/desarrollo/patternfly$ npm install @patternfly/react-core --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@patternfly%2freact-core - Not found
npm ERR! 404 
npm ERR! 404  '@patternfly/react-core@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/usuario/.npm/_logs/2020-08-06T10_07_07_982Z-debug.log
usuario@laika:~/desarrollo/patternfly$ cat /home/usuario/.npm/_logs/2020-08-06T10_07_07_982Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@patternfly/react-core',
1 verbose cli   '--save' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose npm-session 6cb3d6aefadb6bac
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@patternfly%2freact-core 189ms
8 http fetch GET 404 https://registry.npmjs.org/@patternfly%2freact-core 50ms
9 silly fetchPackageMetaData error for @patternfly/react-core@latest 404 Not Found - GET https://registry.npmjs.org/@patternfly%2freact-core - Not found
10 timing stage:rollbackFailedOptional Completed in 3ms
11 timing stage:runTopLevelLifecycles Completed in 282ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@patternfly%2freact-core - Not found
12 verbose stack     at res.buffer.catch.then.body (/usr/share/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose statusCode 404
14 verbose pkgid @patternfly/react-core@latest
15 verbose cwd /home/usuario/desarrollo/patternfly
16 verbose Linux 5.4.0-42-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "@patternfly/react-core" "--save"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@patternfly%2freact-core - Not found
22 error 404
23 error 404 '@patternfly/react-core@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]
usuario@laika:~/desarrollo/patternfly$
```

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

It's a bug.

**What is your product and what release version are you targeting?**

Ubuntu 20.04.
node@v10.19.0
npm@6.14.4
@patternfly/react-core

**Comment by tlabaj** [comment]
cc @redallen

**Comment by redallen** [comment]
I'm on Ubuntu 20.04 and run this command daily without problem.

https://registry.npmjs.org/@patternfly%2freact-core shows JSON in my web browser.

https://www.npmjs.com/package/@patternfly/react-core happily shows our package with a `latest` tag.

This looks like a problem with the NPM registry rather than PatternFly, closing.
