### ISSUE TITLE
Possible issue with React TableHeader SASS/CSS

### ISSUE THREAD

**Issue by willieseabrook** [patternfly/patternfly-react#5320]
**Describe the issue. What is the expected and unexpected behavior?**

See the issue I've filed at dart-sass https://github.com/sass/dart-sass/issues/1186 where they have suggested I debug the TableHeader SASS.

However, I don't know how I would approach that, so am filing an issue here.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Steps are provided at https://github.com/sass/dart-sass/issues/1186 and the test repo is at https://github.com/willieseabrook/nextjs-with-patternfly/

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

There is a workaround - use the deprecated node-sass module

**Comment by fabianishere** [comment]
I have stumbled upon the same issue, getting the following error while using PatternFly in conjunction with Next.js:

> TypeError: Cannot convert object to primitive value
        at escapeHtml (/react-dom/cjs/react-dom-server.node.development.js:1140:16)
        at escapeTextForBrowser (/react-dom/cjs/react-dom-server.node.development.js:1211:10)
        at quoteAttributeValueForBrowser (/react-dom/cjs/react-dom-server.node.development.js:1222:16)
        at createMarkupForProperty (/react-dom/cjs/react-dom-server.node.development.js:1262:25)
        at createOpenTagMarkup (/react-dom/cjs/react-dom-server.node.development.js:3225:16)
        at ReactDOMServerRenderer.renderDOM (/react-dom/cjs/react-dom-server.node.development.js:4232:15)
        at ReactDOMServerRenderer.render ()
        at ReactDOMServerRenderer.read (/react-dom/cjs/react-dom-server.node.development.js:3690:29)
        at renderToString (/react-dom/cjs/react-dom-server.node.development.js:4298:27)
        at Object.renderPage (/next/dist/next-server/server/render.js:53:854)

After debugging, it seems like React is choking on a prop called `___dart_isolate_tags_`, which seems related to https://github.com/dart-lang/sdk/issues/38967. Basically, Dart pollutes the `Object` constructor, which may cause trouble as is the case here.

Replacing some of the uses of `Object` in the PatternFly codebase resolves the issue for me. For instance, in [header-row.tsx](https://github.com/patternfly/patternfly-react/blob/main/packages/react-table/src/components/Table/base/header-row.tsx):
```diff
export const HeaderRow: React.FunctionComponent<HeaderRowProps> = ({
  rowData,
  rowIndex,
  renderers,
-  onRow = () => Object
+  onRow = () => ({})
}: HeaderRowProps) =>
```
