### ISSUE TITLE
Select references `navigator` before its initialized which break SSR builds

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/patternfly-react#6871]
**Describe the issue. What is the expected and unexpected behavior?**

Select references browser `navigator` in props initialization which breaks SSR builds

https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Select/Select.tsx#L227. This initialization code should be in `useEffect` after the component is in a browser environment. I believe you have some `isBrowser` helper method in this repo already.

It also trickles down to any component using Select like: https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
importing the select component in a next.js app.

```
error - node_modules/@patternfly/react-core/dist/js/components/Select/Select.js (867:23) @ eval
ReferenceError: navigator is not defined
null
ReferenceError: navigator is not defined
    at eval (webpack-internal:///./node_modules/@patternfly/react-core/dist/js/components/Select/Select.js:1165:22)
    at Object../node_modules/@patternfly/react-core/dist/js/components/Select/Select.js (/home/martin/insights/frontend-components/packages/docs/.next/server/pages/_app.js:3949:1)
    at __webpack_require__ (/home/martin/insights/frontend-components/packages/docs/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/@patternfly/react-core/dist/js/components/Select/index.js:9:22)
    at Object../node_modules/@patternfly/react-core/dist/js/components/Select/index.js (/home/martin/insights/frontend-components/packages/docs/.next/server/pages/_app.js:4004:1)
    at __webpack_require__ (/home/martin/insights/frontend-components/packages/docs/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/@patternfly/react-core/dist/js/components/CalendarMonth/CalendarMonth.js:16:18)
    at Object../node_modules/@patternfly/react-core/dist/js/components/CalendarMonth/CalendarMonth.js (/home/martin/insights/frontend-components/packages/docs/.next/server/pages/_app.js:924:1)
    at __webpack_require__ (/home/martin/insights/frontend-components/packages/docs/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/@patternfly/react-core/dist/js/components/CalendarMonth/index.js:9:22)

```

Its bug, it the LTS version of the react-core. We kind of need it to be fixed ASAP is we don't want to get stuck on later version.

**Comment by kmcfaul** [comment]
@Hyperkid123 I've put up a PR to resolve this issue, and in the interim it should be able to be worked around by passing in `inputAutoComplete` manually to not hit the `navigator` check.

**Comment by Hyperkid123** [comment]
@kmcfaul thank you! is it possible to release a new lts version sooner than usual?

**Comment by tlabaj** [comment]
@Hyperkid123 is it possible for you to pick up a pre-release version?  We have not done any testing yet.  W should release by the end of next week.
cc @mcarrano
