### ISSUE TITLE
Bug -DataList - drag drop results in error

### ISSUE THREAD

**Issue by edewit** [patternfly/patternfly-react#7637]
**Describe the problem**
DataList drag and drop no longer works but gives error:

```
Truncate-a84c533a.js:3996 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at Truncate-a84c533a.js:3996:24
    at Array.forEach (<anonymous>)
    at DataList.move (Truncate-a84c533a.js:3995:23)
    at DataList.dragOver0 (Truncate-a84c533a.js:4072:22)
    at DataList.dragOver (Truncate-a84c533a.js:4087:22)
    at HTMLUnknownElement.callCallback (react-dom.v17.0.2.js:3952:14)
    at Object.invokeGuardedCallbackDev (react-dom.v17.0.2.js:4001:16)
    at invokeGuardedCallback (react-dom.v17.0.2.js:4063:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.v17.0.2.js:4077:25)
    at executeDispatch (react-dom.v17.0.2.js:8250:3)
```

**How do you reproduce the problem?**
When you drop the item that has been dragged it results in error above see codesandbox:

https://codesandbox.io/s/focused-water-soey9j?file=/index.js

**Expected behavior**
No error ;)

**Is this issue blocking you?**
No we can update to the new beta feature: https://www.patternfly.org/v4/components/data-list#draggable

**Comment by nicolethoen** [comment]
@edewit I believe the props used to implement the drag and drop feature of the data list is deprecated.
In fact we are in the process of further updating and enhancing our implementation of the beta DragDrop component used in the beta example you referenced. You can follow that effort in the issue linked above.
But I don't believe we will be making any changes to the deprecated features of the DataList component.
